import type { ImageSourcePropType } from 'react-native';

export const baubookImages = {
  logo: require('../../../assets/baubook/logo-completo-transparent.png') as ImageSourcePropType,
  homeTabAvatar: require('../../../assets/baubook/brand/avatar_instagram_round.png') as ImageSourcePropType,
  logoOriginal: require('../../../assets/baubook/logo-completo.png') as ImageSourcePropType,
  avatar: require('../../../assets/baubook/avatar-rotondo-transparent.png') as ImageSourcePropType,
  avatarOriginal: require('../../../assets/baubook/avatar-rotondo.png') as ImageSourcePropType,
  appIcon: require('../../../assets/icon.png') as ImageSourcePropType,
  appIconOriginal: require('../../../assets/baubook/icona-app.png') as ImageSourcePropType,
  tabHome: require('../../../assets/baubook/tab-home-badge.png') as ImageSourcePropType,
  socialIntro: require('../../../assets/baubook/social/post-cose-baubook.png') as ImageSourcePropType,
  socialBeta: require('../../../assets/baubook/social/post-beta-in-arrivo.png') as ImageSourcePropType,
  socialPromises: require('../../../assets/baubook/social/post-tre-promesse.png') as ImageSourcePropType,
  homeSafety: {
    scout: require('../../../assets/baubook/home/safety_scout.png') as ImageSourcePropType,
  },
  safetyCircles: {
    lostHelp: require('../../../assets/baubook/safety-circles/lost_help.png') as ImageSourcePropType,
  },
  quickActions: {
    walk: require('../../../assets/baubook/quick-actions/walk.png') as ImageSourcePropType,
    map: require('../../../assets/baubook/quick-actions/map.png') as ImageSourcePropType,
    help: require('../../../assets/baubook/quick-actions/help.png') as ImageSourcePropType,
    profile: require('../../../assets/baubook/quick-actions/profile.png') as ImageSourcePropType,
  },
  badges: {
    beta: require('../../../assets/baubook/badges/beta.png') as ImageSourcePropType,
    inArrivo: require('../../../assets/baubook/badges/in-arrivo.png') as ImageSourcePropType,
    novita: require('../../../assets/baubook/badges/novita.png') as ImageSourcePropType,
    nonDisponibile: require('../../../assets/baubook/badges/non-disponibile.png') as ImageSourcePropType,
    betaAndroidStore: require('../../../assets/baubook/badges/beta-android-store.png') as ImageSourcePropType,
  },
  dangerCircles: {
    suspectedPoison: require('../../../assets/baubook/danger-circles/suspicious_food.png') as ImageSourcePropType,
    looseDog: require('../../../assets/baubook/danger-circles/loose_dog.png') as ImageSourcePropType,
    unsafeArea: require('../../../assets/baubook/danger-circles/unsafe_area.png') as ImageSourcePropType,
    traffic: require('../../../assets/baubook/danger-circles/traffic.png') as ImageSourcePropType,
    brokenFence: require('../../../assets/baubook/danger-circles/broken_fence.png') as ImageSourcePropType,
    other: require('../../../assets/baubook/danger-circles/other.png') as ImageSourcePropType,
  },
  icons: {
    map: require('../../../assets/baubook/icons/01_dove_andare_mappa.png') as ImageSourcePropType,
    dogArea: require('../../../assets/baubook/icons/02_aree_cani.png') as ImageSourcePropType,
    walks: require('../../../assets/baubook/icons/03_passeggiate_insieme.png') as ImageSourcePropType,
    friends: require('../../../assets/baubook/icons/04_amici_a_4_zampe.png') as ImageSourcePropType,
    reports: require('../../../assets/baubook/icons/05_segnalazioni.png') as ImageSourcePropType,
    safety: require('../../../assets/baubook/icons/06_sicurezza.png') as ImageSourcePropType,
    neighbours: require('../../../assets/baubook/icons/07_aiuto_tra_vicini.png') as ImageSourcePropType,
    lostDog: require('../../../assets/baubook/icons/08_mi_sono_perso.png') as ImageSourcePropType,
    sighting: require('../../../assets/baubook/icons/09_visto_avvistamento.png') as ImageSourcePropType,
    recovered: require('../../../assets/baubook/icons/10_recuperato.png') as ImageSourcePropType,
    checkin: require('../../../assets/baubook/icons/11_io_sono_qui_checkin.png') as ImageSourcePropType,
    calendar: require('../../../assets/baubook/icons/12_eventi_orari.png') as ImageSourcePropType,
    notifications: require('../../../assets/baubook/icons/13_notifiche.png') as ImageSourcePropType,
    dogProfile: require('../../../assets/baubook/icons/14_profilo_cane.png') as ImageSourcePropType,
    vet: require('../../../assets/baubook/icons/15_veterinario.png') as ImageSourcePropType,
    messages: require('../../../assets/baubook/icons/16_messaggi.png') as ImageSourcePropType,
    favorites: require('../../../assets/baubook/icons/17_preferiti.png') as ImageSourcePropType,
    danger: require('../../../assets/baubook/icons/18_pericolo.png') as ImageSourcePropType,
    suspiciousFood: require('../../../assets/baubook/icons/19_bocconi_sospetti.png') as ImageSourcePropType,
    route: require('../../../assets/baubook/icons/20_itinerari_percorsi.png') as ImageSourcePropType,
    reviews: require('../../../assets/baubook/icons/21_recensioni.png') as ImageSourcePropType,
    camera: require('../../../assets/baubook/icons/22_foto_camera.png') as ImageSourcePropType,
    stories: require('../../../assets/baubook/icons/23_storie_video.png') as ImageSourcePropType,
    phoneVerify: require('../../../assets/baubook/icons/24_verifica_telefono.png') as ImageSourcePropType,
    privacy: require('../../../assets/baubook/icons/25_privacy.png') as ImageSourcePropType,
    blockUser: require('../../../assets/baubook/icons/26_blocca_utente.png') as ImageSourcePropType,
    moderation: require('../../../assets/baubook/icons/27_moderazione_report.png') as ImageSourcePropType,
    ban: require('../../../assets/baubook/icons/28_ban_sospensione.png') as ImageSourcePropType,
    settings: require('../../../assets/baubook/icons/29_impostazioni.png') as ImageSourcePropType,
    search: require('../../../assets/baubook/icons/30_cerca.png') as ImageSourcePropType,
    filters: require('../../../assets/baubook/icons/31_filtri.png') as ImageSourcePropType,
    time: require('../../../assets/baubook/icons/32_orario.png') as ImageSourcePropType,
    sun: require('../../../assets/baubook/icons/33_al_sole.png') as ImageSourcePropType,
    shade: require('../../../assets/baubook/icons/34_ombra.png') as ImageSourcePropType,
    water: require('../../../assets/baubook/icons/35_acqua_fontanella.png') as ImageSourcePropType,
    dogSitter: require('../../../assets/baubook/icons/36_dog_sitter.png') as ImageSourcePropType,
    food: require('../../../assets/baubook/icons/37_crocche_cibo.png') as ImageSourcePropType,
    holidays: require('../../../assets/baubook/icons/38_vacanze_pet_friendly.png') as ImageSourcePropType,
    petShop: require('../../../assets/baubook/icons/39_negozi_pet.png') as ImageSourcePropType,
  },
  brand: {
    avatarInstagramRound: require('../../../assets/baubook/brand/avatar_instagram_round.png') as ImageSourcePropType,
  },

};
